name: Build Linux DB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_db:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Build Linux DB with build_db.py
      run: ./.github/build_db.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
