name: Build Linux DB

on:
  schedule:
  - cron:  "*/20 * * * *"
  workflow_dispatch:

jobs:
  build_db:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build Linux DB with build_db.py
      run: ./.github/build_db.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
